workspace = {members = ["abc320", "typical90"],exclude = []}
[package]
name = "algorithm_v1_70_0"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
